# See: https://rust-lang.github.io/mdBook/format/config.html
[book]
authors = ["minami", "johannes"]
language = "ja"
multilingual = false
src = "src"
title = "DeFi Book"

[output.html]
default-theme = "rust"

[build]
build-dir = "docs"